### ISSUE TITLE
User Story - CRUD Operations on Properties

### ISSUE THREAD

**Issue by adrianns9** [AdamYoshi/Cody_Stride-soen341projectF2023#21]
As a user, specifically a broker, I want to be able to add and remove properties that I wish to sell.

Task Breakdown:
- [x]  #2 
- [x]  #12 
- [x]  #13 
- [x]  #14

**Comment by AdamYoshi** [comment]
Acceptance Test:
User inputs the title of the property, where the price, location and type of property (e.g: house, triplex, etc.) are mentioned
User writes the description of the property
User adds images of the property
User presses the "Post Property" button
User should see the property listing when viewing his account
User selects the property from his list of properties
User clicks on the "Delete Property" button
User shouldn't be able to see the property on his account anymore
